<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Manoksha.Api</RootNamespace>
    <UserSecretsId>manoksha-api-local</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Manoksha.Hosting\Manoksha.Hosting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Manoksha.IntegrationTests" />
  </ItemGroup>
</Project>
