using System.Text.RegularExpressions;
using Manoksha.Application.Abstractions;
using Manoksha.Application.Security;
using Manoksha.Modules.Catalog.Contracts;
using Manoksha.Modules.Catalog.Domain;
using Manoksha.Persistence;
using Manoksha.SharedKernel;
using Microsoft.EntityFrameworkCore;
using Npgsql;

namespace Manoksha.Modules.Catalog.Application;

internal sealed partial class BarcodeService(
    ManokshaDbContext db,
    IUnitOfWork unitOfWork,
    IAuditWriter audit,
    ICurrentUser currentUser,
    ICatalogLookup lookup,
    IClock clock) : IItemBarcodeIssuer, ICatalogBarcodes
{
    public async Task<IssuedBarcode> IssueForItemAsync(Guid skuId, Guid inventoryItemId, CancellationToken cancellationToken = default)
    {
        await EnsureSkuAsync(skuId, cancellationToken);
        var seq = await db.Database.SqlQuery<long>($"SELECT nextval('catalog.internal_barcode_seq') AS \"Value\"").SingleAsync(cancellationToken);
        var barcode = new Barcode(Gtin.CreateInternalEan13(seq), skuId, inventoryItemId, BarcodeKind.InternalEan13, currentUser.UserIdOrNull, clock.UtcNow);
        db.Add(barcode);
        return new IssuedBarcode(barcode.Id, barcode.Code);
    }

    public async Task<CatalogBarcode?> FindAsync(string code, CancellationToken cancellationToken = default)
    {
        var trimmed = (code ?? string.Empty).Trim();
        var barcode = await db.Set<Barcode>().AsNoTracking().SingleOrDefaultAsync(b => b.Code == trimmed, cancellationToken);
        if (barcode is null)
        {
            return null;
        }
        var sku = await lookup.FindSkuAsync(barcode.SkuId, cancellationToken);
        var values = await (
            from x in db.Set<VariantAttributeValue>()
            join a in db.Set<AttributeDefinition>() on x.AttributeId equals a.Id
            join o in db.Set<AttributeOption>() on x.OptionId equals o.Id
            where x.VariantId == sku!.VariantId
            select new AttributeValue(a.Name, o.Value)).AsNoTracking().ToListAsync(cancellationToken);
        return new CatalogBarcode(barcode.Code, barcode.Kind.ToString(), barcode.Status == RecordStatus.Active, barcode.InventoryItemId, sku!, values);
    }

    public Task<BarcodeDto> GenerateInternalAsync(Guid skuId, string reason, CancellationToken ct)
    {
        CatalogSetupService.RequireReason(reason);
        return unitOfWork.ExecuteInTransactionAsync(async innerCt =>
        {
            await EnsureSkuAsync(skuId, innerCt);
            var seq = await db.Database.SqlQuery<long>($"SELECT nextval('catalog.internal_barcode_seq') AS \"Value\"").SingleAsync(innerCt);
            var barcode = new Barcode(Gtin.CreateInternalEan13(seq), skuId, null, BarcodeKind.InternalEan13, currentUser.UserIdOrNull, clock.UtcNow);
            db.Add(barcode);
            await audit.RecordAsync(new AuditRecord("catalog.barcode.generated", "Barcode", barcode.Id.ToString(), After: new { barcode.Code, skuId }, Reason: reason), innerCt);
            return ToDto(barcode);
        }, ct);
    }

    public Task<BarcodeDto> RegisterExternalAsync(Guid skuId, RegisterBarcodeRequest r, CancellationToken ct)
    {
        CatalogSetupService.RequireReason(r.Reason);
        var code = (r.Code ?? string.Empty).Trim();
        if (!ExternalCodePattern().IsMatch(code))
        {
            throw new BusinessRuleException("BARCODE_INVALID", "Barcode must be 4–40 characters: letters, digits or '-'.", 400);
        }
        if (code.All(char.IsAsciiDigit) && code.Length is 8 or 12 or 13 or 14 && !Gtin.IsValidGtin(code))
        {
            throw new BusinessRuleException("BARCODE_CHECK_DIGIT_INVALID", "This EAN/UPC code has an invalid check digit. Please re-scan it.", 400);
        }
        if (code.StartsWith(Gtin.InternalPrefix, StringComparison.Ordinal) && code.Length == 13)
        {
            throw new BusinessRuleException("BARCODE_RESERVED_RANGE", "Codes starting with 29 are reserved for barcodes generated by this system.", 400);
        }
        return unitOfWork.ExecuteInTransactionAsync(async innerCt =>
        {
            await EnsureSkuAsync(skuId, innerCt);
            var barcode = new Barcode(code, skuId, null, BarcodeKind.External, currentUser.UserIdOrNull, clock.UtcNow);
            db.Add(barcode);
            await audit.RecordAsync(new AuditRecord("catalog.barcode.registered", "Barcode", barcode.Id.ToString(), After: new { barcode.Code, skuId }, Reason: r.Reason), innerCt);
            try
            {
                await db.SaveChangesAsync(innerCt);
            }
            catch (DbUpdateException ex) when (ex.InnerException is PostgresException { SqlState: PostgresErrorCodes.UniqueViolation })
            {
                throw new ConflictException("BARCODE_EXISTS", "This barcode is already registered (codes are never reused).");
            }
            return ToDto(barcode);
        }, ct);
    }

    public Task<BarcodeDto> RetireAsync(Guid barcodeId, RetireBarcodeRequest r, CancellationToken ct)
    {
        CatalogSetupService.RequireReason(r.Reason);
        return unitOfWork.ExecuteInTransactionAsync(async innerCt =>
        {
            var barcode = await db.Set<Barcode>().SingleOrDefaultAsync(b => b.Id == barcodeId, innerCt) ?? throw NotFound();
            barcode.Retire(currentUser.UserId, r.Reason, clock.UtcNow);
            await audit.RecordAsync(new AuditRecord("catalog.barcode.retired", "Barcode", barcodeId.ToString(), After: new { barcode.Code }, Reason: r.Reason), innerCt);
            return ToDto(barcode);
        }, ct);
    }

    /// <summary>Records label printing. Printing again is a reprint of the same identity — nothing new is created.</summary>
    public Task<IReadOnlyList<LabelDto>> PrintAsync(PrintLabelsRequest r, CancellationToken ct)
    {
        var ids = (r.BarcodeIds ?? []).Distinct().ToList();
        if (ids.Count is 0 or > 200 || r.Copies is < 1 or > 100)
        {
            throw new BusinessRuleException("PRINT_REQUEST_INVALID", "Select 1–200 barcodes and 1–100 copies.", 400);
        }
        return unitOfWork.ExecuteInTransactionAsync<IReadOnlyList<LabelDto>>(async innerCt =>
        {
            var rows = await (
                from b in db.Set<Barcode>()
                join s in db.Set<Sku>() on b.SkuId equals s.Id
                join v in db.Set<Variant>() on s.VariantId equals v.Id
                join p in db.Set<Product>() on s.ProductId equals p.Id
                where ids.Contains(b.Id)
                select new { b.Id, b.Code, b.Kind, b.Status, ProductName = p.Name, VariantName = v.Name, SkuCode = s.Code }).ToListAsync(innerCt);
            if (rows.Count != ids.Count)
            {
                throw NotFound();
            }
            if (rows.Any(x => x.Status != RecordStatus.Active))
            {
                throw new BusinessRuleException("BARCODE_RETIRED", "Retired barcodes cannot be printed.");
            }
            var printed = await db.Set<BarcodePrint>().Where(x => ids.Contains(x.BarcodeId)).Select(x => x.BarcodeId).Distinct().ToListAsync(innerCt);
            var labels = new List<LabelDto>();
            foreach (var row in rows)
            {
                var reprint = printed.Contains(row.Id);
                db.Add(new BarcodePrint(row.Id, r.Copies, reprint, currentUser.UserIdOrNull, clock.UtcNow));
                labels.Add(new LabelDto(row.Id, row.Code, row.Kind.ToString(), row.ProductName, row.VariantName, row.SkuCode, r.Copies, reprint));
            }
            return labels;
        }, ct);
    }

    public async Task<ScanResultDto> LookupAsync(string code, CancellationToken ct)
    {
        var trimmed = (code ?? string.Empty).Trim();
        var row = await (
            from b in db.Set<Barcode>()
            join s in db.Set<Sku>() on b.SkuId equals s.Id
            join v in db.Set<Variant>() on s.VariantId equals v.Id
            join p in db.Set<Product>() on s.ProductId equals p.Id
            where b.Code == trimmed
            select new { b, s, v, p }).AsNoTracking().SingleOrDefaultAsync(ct)
            ?? throw new NotFoundException("BARCODE_NOT_FOUND", "No product is registered for this barcode.");
        if (row.b.Status != RecordStatus.Active)
        {
            throw new BusinessRuleException("BARCODE_RETIRED", "This barcode has been retired. Use the item's current label.", 410);
        }

        var values = await (
            from x in db.Set<VariantAttributeValue>()
            join a in db.Set<AttributeDefinition>() on x.AttributeId equals a.Id
            join o in db.Set<AttributeOption>() on x.OptionId equals o.Id
            where x.VariantId == row.v.Id
            select new VariantValueDto(a.Id, a.Name, o.Id, o.Value)).AsNoTracking().ToListAsync(ct);

        return new ScanResultDto(row.b.Code, row.b.Kind.ToString(), row.b.InventoryItemId, row.s.Id, row.s.Code, row.v.Id, row.v.Name, values,
            row.p.Id, row.p.Name, row.p.Status.ToString(), row.p.TrackingMode.ToString(), row.p.AvailableForRetail, row.p.AvailableForReseller);
    }

    private async Task EnsureSkuAsync(Guid skuId, CancellationToken ct)
    {
        if (!await db.Set<Sku>().AnyAsync(s => s.Id == skuId, ct))
        {
            throw new NotFoundException("SKU_NOT_FOUND", "SKU not found.");
        }
    }

    private static BarcodeDto ToDto(Barcode b) => new(b.Id, b.Code, b.Kind.ToString(), b.Status.ToString(), b.InventoryItemId, b.CreatedAt, 0, null, b.RetireReason);

    private static NotFoundException NotFound() => new("BARCODE_NOT_FOUND", "Barcode not found.");

    [GeneratedRegex("^[A-Za-z0-9-]{4,40}$")]
    private static partial Regex ExternalCodePattern();
}
