<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Manoksha.Integrations</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MailKit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\Manoksha.Application\Manoksha.Application.csproj" />
  </ItemGroup>
</Project>
