<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Manoksha.Modules.Pricing</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\Manoksha.Persistence\Manoksha.Persistence.csproj" />
    <ProjectReference Include="..\Manoksha.Modules.Catalog\Manoksha.Modules.Catalog.csproj" />
    <ProjectReference Include="..\Manoksha.Modules.Resellers\Manoksha.Modules.Resellers.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Manoksha.UnitTests" />
    <InternalsVisibleTo Include="Manoksha.IntegrationTests" />
  </ItemGroup>
</Project>
